center/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from center import settings

urlpatterns = [

    path("admin/", admin.site.urls),
    path('', include('post.urls')),
    path('profile/', include('profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from center import settings 
from post import views
from django.conf.urls.static import static
app_name = 'post'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.index, name = 'home'),
    path('create_post/', views.create_post, name='create_post'),
    path('register/',views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('<uuid:uuid>/like/', views.like_view, name='like'),
    path('<uuid:uuid>/comment/', views.comment_view, name='comment'),
    path('explore/', views.explore_view, name='explore'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('<username>/', views.UserProfile, name='userProfile'),
    path('<str:username>/follow/', views.follow_user, name='follow'),
    path('<str:username>/unfollow/', views.unfollow_user, name='unfollow'),
]

post/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.timesince import timesince
from django.utils import timezone
from center import settings
from profiles.models import Profile

class Post(models.Model):
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    caption = models.TextField(max_length=1000, blank=True)
    likes = models.IntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=100, blank=True)
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4)

    def __str__(self):
        return f"Post {self.uuid}"
    

class Comment(models.Model):
    content = models.CharField(max_length=200, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f"Comment on {self.post}"

    class Meta:
        ordering = ['-created']

    @property
    def time_diff(self):
        now = timezone.now()
        diff = now - self.created
        if diff.days > 0:
            return f"{diff.days} days ago"
        elif diff.seconds // 3600 > 0:
            return f"{diff.seconds // 3600} hours ago"
        elif diff.seconds // 60 > 0:
            return f"{diff.seconds // 60} minutes ago"
        else:
            return "Just now"

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user} likes {self.post}'

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
class Follower(models.Model):
    follower = models.ForeignKey(User, related_name='following_set', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='followers_set', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('follower', 'following')

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_pics', default='profile_pics/default.jpg', blank=True)
    bio = models.TextField(max_length=300, blank=True)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    follower_count = models.IntegerField(default=0)
    following_count = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)  

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    def get_profile_image_url(self):
        if self.profile_image and hasattr(self.profile_image, 'url'):
            return self.profile_image.url
        return  'https://picsum.photos/id/64/30/30'

    def __str__(self):
        return f'{self.user.username} Profile'


from django.contrib.auth.models import User
from django.db import models

class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f"{self.follower.username} is following {self.following.username}"

profiles/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.paginator import Paginator
from .models import Profile
from post.models import Post
from .models import Follow
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def UserProfile(request, username):
    profile_user = get_object_or_404(User, username=username)
    profile, created = Profile.objects.get_or_create(user=profile_user)

    posts = Post.objects.filter(created_by=profile_user).order_by('-created_at')
    posts_count = posts.count()
    following_count = Follow.objects.filter(follower=profile_user).count()
    followers_count = Follow.objects.filter(following=profile_user).count()
    follow_status = Follow.objects.filter(following=profile_user, follower=request.user).exists()

    paginator = Paginator(posts, 8)
    page_number = request.GET.get('page')
    posts_paginator = paginator.get_page(page_number)
    
   
    context = {
        'profile_user': profile_user,
        'profile': profile,
        'posts_count': posts_count,
        'following_count': following_count,
        'followers_count': followers_count,
        'posts_paginator': posts_paginator,
        'follow_status': follow_status,
       
    }
    return render(request, 'pages/profile.html', context)


@login_required
def follow_user(request, username):
    following_user = User.objects.get(username=username)
    Follow.objects.get_or_create(follower=request.user, following=following_user)
    referer_url = request.META.get('HTTP_REFERER')
    return redirect(referer_url)

@login_required
def unfollow_user(request, username):
    following_user = User.objects.get(username=username)
    Follow.objects.filter(follower=request.user, following=following_user).delete()
    referer_url = request.META.get('HTTP_REFERER')
    return redirect(referer_url)

templates/pages/explore.html
{% extends 'base/base.html' %}

{% block title %}Keşfet - Instagram Clone{% endblock %}

{% block content %}
<div class="row">
  <div class="col-3">
      {% include 'components/navbar.html' %}
  </div>
  <div class="col-9">
    <div class="row">
    <div class="col-sm-8">
        <div class="container ">
          <ul class="list-inline mt-5">
            <li class="list-inline-item h6"><a class="text-decoration-none text-dark" href="{% url 'post:home' %}">Senin için</a></li>
            <li class="list-inline-item h6"><a class="text-decoration-none text-dark" href="{% url 'post:explore' %}">Keşfet</a></li>
        </ul>
        <hr>
            <div class="row mt-3">
                {% for post in top_posts %}
                <div class="col-sm-4">
                  <div class="mb-3"><img src="{{ post.image.url }}" class="w-100" alt="">
                  </div>
                </div>
                {% endfor %}
            </div>
    </div>
    </div>
    <div class="col">
      <div class="mt-3">
          <h6>Önerilen Kullanıcılar</h6>
          <ul class="list-group">
              {% for user in random_users %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="d-flex align-items-center">
                      <img src="https://picsum.photos/id/64/30/30" class="rounded-circle me-2" style="max-width: 40px;" alt="Profil Fotoğrafı">
                      <a href="{% url 'profiles:userProfile' username=user.username %}" class="text-decoration-none text-dark"><small>{{ user.username }}</small></a>
                  </div>
                  <div>
                      <button type="button" class="btn btn-primary">Takip Et</button>
                  </div>
              </li>
              {% endfor %}
          </ul>
      </div>
  </div>
</div>
</div>
  </div>
</div>
{% endblock %}

templates/pages/home.html
{% extends 'base/base.html' %}

{% block title %}Ana Sayfa - Instagram Clone{% endblock %}
{% if request.user.is_authenticated %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                {% include 'components/navbar.html' %}
            </div>
            <div class="col-sm-9">
                <div class="container">
                    <ul class="list-inline mt-5">
                        <li class="list-inline-item h6"><a class="text-decoration-none text-dark" href="{% url 'post:home' %}">Senin İçin</a></li>
                        <li class="list-inline-item h6"><a class="text-decoration-none text-dark" href="{% url 'post:explore' %}">Keşfet</a></li>
                    </ul>
                    <hr>
                    <div class="row">
                        <div class="col-sm-9">
                            {% for post in posts reversed %}
                                <div class="card w-75 mx-auto border border-0">
                                  <div class="card-header bg-white border border-0">
                                      <li class="list-inline-item"><img src="https://picsum.photos/id/64/30/30" class="rounded-circle" alt=""><a href="#" class="text-decoration-none text-dark ms-2"> {{ post.created_by }} </a></li>
                                      <li class="list-inline-item">- {{ post.created_at|timesince }} önce</li>
                                  </div>
                                  <div class="card-body">
                                      <img src="{{ post.image.url }}" class="w-100">
                                      <div>
                                          <li class="list-inline-item mt-2">
                                              <form method="POST" action="{% url 'post:like' uuid=post.uuid %}">
                                                  {% csrf_token %}
                                                  <button type="submit" class="btn btn-link" >
                                                      {% if user_liked_post %}
                                                          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  fill="red" class="bi bi-heart" viewBox="0 0 16 16" >
                                                              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.920 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/> 
                                                          </svg>
                                                      {% else %}
                                                          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="" class="bi bi-heart" viewBox="0 0 16 16">
                                                              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.920 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/> 
                                                          </svg>
                                                      {% endif %}
                                                  </button>
                                              </form>
                                          </li>
                                          <li class="list-inline-item mt-2">
                                              <a href="#" class="text-dark" data-bs-toggle="modal" data-bs-target="#commentModal">
                                                  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                                                      <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                                                  </svg>
                                              </a>
                                          </li>
                                          <div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
                                              <div class="modal-dialog">
                                                  <div class="modal-content">
                                                      <div class="modal-header">
                                                          <h5 class="modal-title" id="commentModalLabel">Yorum Ekle</h5>
                                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                      </div>
                                                      <div class="modal-body">
                                                          <form method="post" action="{% url 'post:comment' post.uuid %}">
                                                              {% csrf_token %}
                                                              {{ comment_form.as_p }}
                                                              <button type="submit" class="btn btn-primary">Yorum Ekle</button>
                                                          </form>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <li class="list-inline-item mt-2 ms-2">
                                              <a href="" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
                                                      <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/>
                                                  </svg></a><div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                                  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                                      <div class="modal-content">
                                                          <div class="">
                                                              <h1 class="modal-title fs-5 text-center mt-2" >Paylaş <button type="button" class="btn-close float-end" data-bs-dismiss="modal" ></button></h1>
                                                              <hr> 
                                                          </div>
                                                          <div class="modal-body">
                                                              <select class="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
                                                                  <option selected>Kime...</option>
                                                                  {% for user in users %}
                                                                  <option>{{ user.username }}</option>
                                                                  {% endfor %}
                                                              </select>   
                                                          </div>
                                                          <div class="d-grid gap-2 p-2 m-2 ">
                                                              <a href="#" class="btn btn-primary" role="button" type="submit" >Gönder</a>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </li>
                                          <li class="list-inline-item mt-2 ms-2 float-end">
                                              <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                                                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
                                              </svg>
                                          </li>
                                          <p class="mt-2 h6" >{{ post.likes }} beğenme</p>
                                          <div>
                                            <span class="me-2 h6">{{ post.created_by }}</span>{{ post.caption }}
                                            <hr>
                                            <div>
                                                {% for tag in post.tags.all %}
                                                    <span class="badge bg-primary">{{ tag.name }}</span>
                                                {% endfor %}
                                            </div>
                                        </div>
                                
                                          {% for comment in post.comment_set.all %}
                                          
                                          
                                          <div class="mt-2"><span class="me-2 h6">{{ comment.author.user.username }}</span>
                                              {{ comment.content }} <span class="float-end">{{ comment.created|timesince }} önce</span></div>
                                          
                                          {% endfor %}
                                          {% for comment in post.comments.all %}
                                            <div class="comment">
                                            <p><strong>{{ comment.author.user.username }}</strong>: {{ comment.content }}</p>
                                            
                                             </div>
                                          {% endfor %}
                                       
                                          
                                      </div>
                                  </div>
                              </div>
                              
                            {% endfor %}
                        </div>
                        <div class="col-sm-3">
                          <div class="mt-3">
                              <h6>Önerilen Kullanıcılar</h6>
                              <ul class="list-group">
                                  {% for user in random_users %}
                                  <li class="list-group-item d-flex justify-content-between align-items-center">
                                      <div class="d-flex align-items-center">
                                          <img src="https://picsum.photos/id/64/30/30" class="rounded-circle me-2" style="max-width: 40px;" alt="Profil Fotoğrafı">
                                          <a href="{% url 'profiles:userProfile' username=user.username %}" class="text-decoration-none text-dark"><small>{{ user.username }}</small></a>
                                      </div>
                                      {% if follow_status %}
                                      <a href="{% url 'profiles:unfollow' username=user.username %}" class="btn btn-danger">Takibi Bırak</a>
                                      {% else %}
                                      <a href="{% url 'profiles:follow' username=user.username %}" class="btn btn-primary">Takip Et</a>
                                      {% endif %}
                                  </li>
                                  {% endfor %}
                              </ul>
                          </div>
                      </div>
                      
                      
                      
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% endif %}

templates/pages/index.html
{% extends 'base/base.html' %}

{% block title %}Instagram - Login{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-6 mt-4 d-none d-sm-block">
        <img class="rounded float-end" src="https://assets-global.website-files.com/5fac161927bf86485ba43fd0/63f491d6e8a97e3434aa6045_Screen%20Shot%202023-02-21%20at%2011.41.07.webp" alt="" width="350px" height="550px">
    </div>
    <div class="col-sm-6">
        <div class="card mt-5" style="width: 20rem;">
            <div class="card-body">
                <div class="text-center" aria-disabled="false" role="button" tabindex="0" style="cursor: pointer;">
                    <i data-visualcompletion="css-img" aria-label="Instagram" class="" role="img" style="background-image: url(&quot;https://static.cdninstagram.com/rsrc.php/v3/yh/r/IS7e616CiR2.png&quot;); background-position: 0px 0px; background-size: 176px 258px; width: 175px; height: 51px; background-repeat: no-repeat; display: inline-block;"></i>
                </div>
                <div>
                    {% for message in messages %}
                         <div class="alert alert-danger" role="alert">
                             <i class="fas fa-exclamation-circle"></i> {{ message }}
                        </div>
                    {% endfor %}
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" name="username" class="form-control bg-light" placeholder="Telefon numarası, kullanıcı adı veya e-posta">
                    </div>
                    <div class="mb-3">
                        <input type="password" name="password" class="form-control bg-light" placeholder="Şifre">
                    </div>
                    <div class="d-grid gap-2 mb-3">
                        <button type="submit" class="btn btn-primary">Giriş Yap</button>
                    </div>
                </form>
                <p class="text-center text-body-secondary">⎯⎯⎯⎯⎯⎯ YA DA ⎯⎯⎯⎯⎯</p>
                <div class="text-center mb-2">
                    <a href="https://www.facebook.com/login.php?skip_api_login=1&api_key=124024574287414&kid_directed_site=0&app_id=124024574287414&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D124024574287414%26locale%3Dtr_TR%26redirect_uri%3Dhttps%253A%252F%252Fwww.instagram.com%252Faccounts%252Fsignup%252F%26response_type%3Dcode%252Cgranted_scopes%26scope%3Demail%26state%3D%257B%2522fbLoginKey%2522%253A%25221p1bpt9p7bi8m62g4bkf2qw3v14mw4pus0lr7w1x2omrb1cx3te%2522%252C%2522fbLoginReturnURL%2522%253A%2522%252Ffxcal%252Fdisclosure%252F%253Fnext%253D%25252F%2522%257D%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3Da4ca348e-95de-4f25-8027-c70426b9b5e3%26tp%3Dunspecified&cancel_url=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fsignup%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D%257B%2522fbLoginKey%2522%253A%25221p1bpt9p7bi8m62g4bkf2qw3v14mw4pus0lr7w1x2omrb1cx3te%2522%252C%2522fbLoginReturnURL%2522%253A%2522%252Ffxcal%252Fdisclosure%252F%253Fnext%253D%25252F%2522%257D%23_%3D_&display=page&locale=tr_TR&pl_dbl=0" class="text-decoration-none text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook me-2" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951" />
                        </svg>Facebook ile giriş yap
                    </a>
                </div>
                <a href="#" class="text-decoration-none text-dark">
                    <p class="my-auto text-center fs-6">Şifreni mi unuttun?</p>
                </a>
            </div>
        </div>
        <div class="card mt-3" style="width: 20rem;">
            <div class="card-body">
                <p class="text-center my-auto">Hesabın yok mu? <a href="{% url 'post:register' %}" class="text-decoration-none text-primary">Kaydol</a></p>
            </div>
        </div>
        <div class="card mt-3 border-light" style="width: 20rem;">
            <p class="py-auto text-center">Uygulamayı indir.</p>
        </div>
        <div class="card border-light" style="width: 20rem;">
            <div class="ms-5">
                <a href="https://play.google.com/store/apps/details?id=com.instagram.android&referrer=ig_mid%3DC361F4B7-808F-42A4-9F9B-6F2844536C84%26utm_campaign%3DloginPage%26utm_content%3Dlo%26utm_source%3Dinstagramweb%26utm_medium%3Dbadge%26original_referrer%3Dhttps://www.google.com/&pli=1"><img width="120px" src="https://static.cdninstagram.com/rsrc.php/v3/yp/r/XUCupIzGmzB.png" alt=""> </a>
                <a class="ms-2" href="https://apps.apple.com/us/app/instagram/id389801252?vt=lo"><img width="95px" src="https://static.cdninstagram.com/rsrc.php/v3/yf/r/BFthdeAc5KC.png" alt=""> </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/profile.html
{% extends 'base/base.html' %}

{% block title %}
    {{ profile_user.username }} Profili
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-sm-3">
                {% include 'components/navbar.html' %}
            </div>
            <div class="col-sm-9">
                <div class="profile">
                    <div class="profile-image">
                        <img src="https://picsum.photos/id/64/100/100" alt="Profil Resmi" class="img-fluid rounded-circle">
                    </div>
                    <div class="profile-user-settings">
                        <h3 class="mt-3">{{ profile_user.username }}</h3>
                        <div class="row">
                            <div class="col">
                                <p><strong>Takipçiler:</strong> {{ followers_count }}</p>
                            </div>
                            <div class="col">
                                <p><strong>Takip Edilen:</strong> {{ following_count }}</p>
                            </div>
                        </div>
                        {% if request.user != profile_user %}
                            <div>
                                {% if follow_status %}
                                    <a href="{% url 'profiles:unfollow' username=profile_user.username %}" class="btn btn-danger">Takibi Bırak</a>
                                {% else %}
                                    <a href="{% url 'profiles:follow' username=profile_user.username %}" class="btn btn-primary">Takip Et</a>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            
            
                <hr>
                <h2 class="mb-4">Postlar</h2>
                <div class="row">
                    {% for post in posts_paginator %}
                        <div class="col-md-4 mb-4">
                            <div class="card">
                                <img src="{{ post.image.url }}" alt="" class="card-img-top">
                                <div class="card-body">
                                    <p class="card-text">{{ post.content }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            
                <div class="pagination justify-content-center">
                    {% if posts_paginator.has_previous %}
                        <a href="?page=1" class="page-link">&laquo; Başlangıç</a>
                        <a href="?page={{ posts_paginator.previous_page_number }}" class="page-link">&lsaquo; Önceki</a>
                    {% endif %}
                    <span class="page-link">{{ posts_paginator.number }} / {{ posts_paginator.paginator.num_pages }}</span>
                    {% if posts_paginator.has_next %}
                        <a href="?page={{ posts_paginator.next_page_number }}" class="page-link">Sonraki &rsaquo;</a>
                        <a href="?page={{ posts_paginator.paginator.num_pages }}" class="page-link">Son &raquo;</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}