center/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from center import settings

urlpatterns = [

    path("admin/", admin.site.urls),
    path('', include('post.urls')),
    path('profile/', include('profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from center import settings 
from post import views
from django.conf.urls.static import static
app_name = 'post'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.index, name = 'home'),
    path('create_post/', views.create_post, name='create_post'),
    path('register/',views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('<uuid:uuid>/like/', views.like_view, name='like'),
    path('<uuid:uuid>/comment/', views.comment_view, name='comment'),
    path('explore/', views.explore_view, name='explore'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('<username>/', views.UserProfile, name='userProfile'),
    path('<str:username>/follow/', views.follow_user, name='follow'),
    path('<str:username>/unfollow/', views.unfollow_user, name='unfollow'),
]

post/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.timesince import timesince
from django.utils import timezone
from center import settings
from profiles.models import Profile

class Post(models.Model):
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    caption = models.TextField(max_length=1000, blank=True)
    likes = models.IntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=100, blank=True)
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4)

    def __str__(self):
        return f"Post {self.uuid}"
    

class Comment(models.Model):
    content = models.CharField(max_length=200, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f"Comment on {self.post}"

    class Meta:
        ordering = ['-created']

    @property
    def time_diff(self):
        now = timezone.now()
        diff = now - self.created
        if diff.days > 0:
            return f"{diff.days} days ago"
        elif diff.seconds // 3600 > 0:
            return f"{diff.seconds // 3600} hours ago"
        elif diff.seconds // 60 > 0:
            return f"{diff.seconds // 60} minutes ago"
        else:
            return "Just now"

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user} likes {self.post}'

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
class Follower(models.Model):
    follower = models.ForeignKey(User, related_name='following_set', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='followers_set', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('follower', 'following')

templates/components/create_post.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Post oluştur:</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_image">Fotoğrafı seçin:</label>
            <input type="file" name="image" id="id_image" class="form-control-file">
            {% if form.post_picture.value %}
            <img src="{{ form.image.value.url }}" class="img-fluid mt-2" alt="Selected Image">
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_caption">Caption:</label>
            <textarea name="caption" id="id_caption" class="form-control" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="id_tags">Tags:</label>
            <input type="text" id="id_tags" class="form-control" placeholder="Enter tags">
            <small id="tagsHelp" class="form-text text-muted">Tag eklemek için enter'a basın.</small>
            <ul id="tagList" class="list-inline mt-2">
                <!-- Tags will be added here -->
            </ul>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Post oluştur.</button>
    </form>
</div>

<!-- Modal for Content Input -->
<div class="modal fade" id="contentModal" tabindex="-1" role="dialog" aria-labelledby="contentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contentModalLabel">İçeriği gir:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <textarea id="contentTextarea" class="form-control" rows="5"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="saveContent">Save</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#saveContent').on('click', function() {
        var content = $('#contentTextarea').val();
        $('#id_content').val(content);
        $('#contentModal').modal('hide');
    });

    $('#id_tags').keypress(function(event) {
        if (event.keyCode === 13) {
            var tag = $(this).val();
            $(this).val('');

            $('#tagList').append('<li class="list-inline-item"><span class="badge bg-secondary">' + tag + '</span></li>');
        }
    });
</script>
{% endblock %}

templates/components/footer.html
<footer class="py-3 my-4 fsm">
    <ul class="nav justify-content-center pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Meta</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Hakkında</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Blog</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">İş Fırsatları</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Yardım</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">API</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Gizlilik</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Koşullar</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Konumlar</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Instagram Lite</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Threads</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Kişi Yükleme ve Hesabı Olmayan Kişiler</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Meta Verified</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Instagram from Meta</p>
</footer>

templates/components/messages.html
{% if messages %}
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        {% for message in messages %}
            <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="me-auto">{{ message.tags }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/components/navbar.html
<nav class="navbar-vertical ">
    <ul class="navbar-nav">
        <div class="text-center mt-3" aria-disabled="false" role="button" tabindex="0" style="cursor: pointer;"><i data-visualcompletion="css-img" 
            aria-label="Instagram" class="" role="img" style="background-image: url(&quot;https://static.cdninstagram.com/rsrc.php/v3/yh/r/IS7e616CiR2.png&quot;);
            background-position: 0px 0px; background-size: 176px 258px; width: 175px; height: 51px; background-repeat: no-repeat; display: 
             inline-block;"></i></div>
        <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-4">
            <a href="{% url 'post:home' %}" class="text-decoration-none d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                    <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
                  </svg>
                <span class="ms-3 text-dark">Ana Sayfa</span>
            </a>
        </li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3"><a href="" class="text-decoration-none d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
          </svg><span class="ms-3 text-dark"> Ara</span></a></li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3"><a href="{% url 'post:explore' %}" class="text-decoration-none d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-compass" viewBox="0 0 16 16">
            <path d="M8 16.016a7.5 7.5 0 0 0 1.962-14.74A1 1 0 0 0 9 0H7a1 1 0 0 0-.962 1.276A7.5 7.5 0 0 0 8 16.016m6.5-7.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0"/>
            <path d="m6.94 7.44 4.95-2.83-2.83 4.95-4.949 2.83 2.828-4.95z"/>
          </svg> <span class="ms-3 text-dark"> Keşfet</span></a></li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3"><a href="" class="text-decoration-none d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-collection-play" viewBox="0 0 16 16">
            <path d="M2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3m2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1m2.765 5.576A.5.5 0 0 0 6 7v5a.5.5 0 0 0 .765.424l4-2.5a.5.5 0 0 0 0-.848z"/>
            <path d="M1.5 14.5A1.5 1.5 0 0 1 0 13V6a1.5 1.5 0 0 1 1.5-1.5h13A1.5 1.5 0 0 1 16 6v7a1.5 1.5 0 0 1-1.5 1.5zm13-1a.5.5 0 0 0 .5-.5V6a.5.5 0 0 0-.5-.5h-13A.5.5 0 0 0 1 6v7a.5.5 0 0 0 .5.5z"/>
          </svg> <span class="ms-3 text-dark"> Reels</span></a></li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3"><a href="" class="text-decoration-none d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-messenger" viewBox="0 0 16 16">
            <path d="M0 7.76C0 3.301 3.493 0 8 0s8 3.301 8 7.76-3.493 7.76-8 7.76c-.81 0-1.586-.107-2.316-.307a.64.64 0 0 0-.427.03l-1.588.702a.64.64 0 0 1-.898-.566l-.044-1.423a.64.64 0 0 0-.215-.456C.956 12.108 0 10.092 0 7.76m5.546-1.459-2.35 3.728c-.225.358.214.761.551.506l2.525-1.916a.48.48 0 0 1 .578-.002l1.869 1.402a1.2 1.2 0 0 0 1.735-.32l2.35-3.728c.226-.358-.214-.761-.551-.506L9.728 7.381a.48.48 0 0 1-.578.002L7.281 5.98a1.2 1.2 0 0 0-1.735.32z"/>
          </svg> <span class="ms-3 text-dark"> Mesajlar</span></a></li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3"><a href="" class="text-decoration-none d-flex align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
          </svg> <span class="ms-3 text-dark"> Bildirimler </span></a></li>
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3">
            <a href="{% url 'post:create_post' %}" class="text-decoration-none d-flex align-items-center" data-toggle="modal" data-target="#createPostModal">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-plus-square" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg> 
                <span class="ms-3 text-dark"> Oluştur</span>
            </a>
        </li>
        <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3">
          <a href="{% url 'profiles:userProfile' username=request.user.username %}" class="text-decoration-none d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="dark" class="bi bi-person-circle" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg> 
              <span class="ms-3 text-dark"> Profil</span>
          </a>
      </li>
      
          <li class="list-group-item d-flex align-items-center border border-0 ms-3 mt-3">
            <a href="{% url 'post:logout' %}" class="text-decoration-none d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
                    <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                  </svg>
                <span class="ms-3 text-dark">Çıkış yap</span>
            </a>
        </li>
      </ul>  
</nav>